#!/bin/sh

APPNAME=$0
TMP_FOLDER=.tmp

usage() {
    echo "$1"
    echo ${APPNAME}": <stackname> <deployment-S3-bucket-name> <region> <deployment-environment> <key-name>"
    echo "stackname                 [REQUIRED]: your cloudformation stack name"
    echo "deployment-S3-bucket-name [REQUIRED]: S3 bucket to store the tempolary template file"
    echo "key-name                  [REQUIRED]: AWS KeyPair name"
    echo "deployment-environment    [REQUIRED]: environment where the stack will be deployed. Valid values: Dev|Test|UAT|Prod"
    echo "region                    [OPTIONAL]: AWS Region where the stack will be deployed"
}

if [ ! -d ${TMP_FOLDER} ]; then
    mkdir ${TMP_FOLDER}
fi

if [ ! -z "$1" ]; then
  STACKNAME=$1
elif [ -z "${STACKNAME}" ]; then
  usage "Please provide the stackname"
  exit 1
fi

if [ ! -z "$2" ]; then
  S3_BUCKET=$2
elif [ -z "${S3_BUCKET}" ]; then
  usage "Please provide the deployment-S3-bucket-name"
  exit 1
fi

if [ ! -z "$3" ]; then
  TARGET_ENV=$3
elif [ -z "${TARGET_ENV}" ]; then
  usage "Please provide Target Environment"
  exit 1
fi

if [ ! -z "$4" ]; then
  BASTION_HOST_KEY_NAME=$4
elif [ -z "${BASTION_HOST_KEY_NAME}" ]; then
  usage "Please provide AWS BastionHost KeyName"
  exit 1
fi

if [ ! -z "$5" ]; then
  REGION=$5
fi 

AWS_REGION=""

if [ ! -z "${REGION}" ]; then
  AWS_REGION="--region ${REGION}"
fi

ROLE_ARN_PARAM=""

if [ ! -z "$ROLE_ARN" ]; then
  ROLE_ARN_PARAM="--role-arn ${ROLE_ARN}"
fi


aws cloudformation package --template-file main-stack.yaml --s3-bucket ${S3_BUCKET} --region ${REGION} --output-template-file ./.tmp/main-stack.yaml

RET=$?

if [ "$RET" = "0" ]; then
  if aws cloudformation describe-stacks ${AWS_REGION} --stack-name ${STACKNAME}  2>/dev/null; then
    echo "Update stack ${STACKNAME}"
    aws cloudformation  update-stack  \
  --template-body file://${TMP_FOLDER}/main-stack.yaml \
  --stack-name ${STACKNAME} \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM  CAPABILITY_AUTO_EXPAND  \
  --parameters  ParameterKey=Environment,ParameterValue=${TARGET_ENV} ParameterKey=BastionHostKeyName,ParameterValue=${BASTION_HOST_KEY_NAME} ${AWS_REGION} ${ROLE_ARN_PARAM}
    exit $?
  else
    echo "Create stack ${STACKNAME}"
    aws cloudformation  create-stack  \
  --template-body file://${TMP_FOLDER}/main-stack.yaml \
  --stack-name ${STACKNAME} \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM  CAPABILITY_AUTO_EXPAND  \
  --parameters  ParameterKey=Environment,ParameterValue=${TARGET_ENV} ParameterKey=BastionHostKeyName,ParameterValue=${BASTION_HOST_KEY_NAME} ${AWS_REGION} ${ROLE_ARN_PARAM}
    exit $?
  fi
else
  echo "Failed"
  exit ${RET}
fi
