# application-subnets.yaml
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
  VpcId:
    Description: VPC ID
    Type: String
  StackName:
    Description: Name of the Stack
    Type: String
    AllowedPattern: '[a-zA-Z0-9_\-]*'
    ConstraintDescription: must be alphanumeric
  PrivateAppSubnet01:
    Description: Private App Subnet 01
    Type: String
  PrivateAppSubnet02:
    Description: Private App Subnet 02
    Type: String
  PrivateAppSubnet03:
    Description: Private App Subnet 03
    Type: String
Resources:
  WebApplicationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      GroupName: WebApplicationSecurityGroup
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 10.0.0.0/24
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '8080'
          CidrIp: 10.0.0.0/24
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - WebApplicationSecurityGroup
        - Key: Env
          Value: !Ref Environment
