# public-subnets.yaml
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
  VpcId:
    Description: VPC ID
    Type: String
  PublicSubnet01Id:
    Description: PublicSubnet01 ID
    Type: String
  PublicSubnet02Id:
    Description: PublicSubnet02 ID
    Type: String
  PublicSubnet03Id:
    Description: PublicSubnet03 ID
    Type: String
  StackName:
    Description: Name of the Stack
    Type: String
    AllowedPattern: '[a-zA-Z0-9_\-]*'
    ConstraintDescription: must be alphanumeric
Resources:
  LoadBlancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Load Balancer Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - BastionHost
        - Key: Env
          Value: !Ref Environment
  WebLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: WebLoadBalancer
      Subnets:
        - !Ref PublicSubnet01Id
        - !Ref PublicSubnet02Id
        - !Ref PublicSubnet03Id
      SecurityGroups:
        - !Ref LoadBlancerSecurityGroup
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - WebLoadBalancer
        - Key: Env
          Value: !Ref Environment
Outputs:
  WebLoadBalancerId:
    Description: Web Load Balancer ID
    Value: !Ref WebLoadBalancer
  WebLoadBalancerDNSName:
    Description: Web Load Balancer DNS Name
    Value: !GetAtt WebLoadBalancer.DNSName
