# main-stack.yaml
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
  BastionHostKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ./vpc-stack.yaml
      Parameters:
        Environment: !Ref Environment
        StackName: !Ref AWS::StackName
  PublicSubnets:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ./public-subnets.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        IgwId: !GetAtt VpcStack.Outputs.IgwId
        StackName: !Ref AWS::StackName
  NatGateway01:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ./nat01-stack.yaml
      Parameters:
        Environment: !Ref Environment
        PublicSubnet01Id: !GetAtt PublicSubnets.Outputs.PublicSubnet01Id
        StackName: !Ref AWS::StackName
  BastionHost:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./bastion-host-stack.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PublicSubnet01Id: !GetAtt PublicSubnets.Outputs.PublicSubnet01Id
        StackName: !Ref AWS::StackName
        KeyName: !Ref BastionHostKeyName
