# nat-stack.yaml
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
  VpcId:
    Description: VPC ID
    Type: String
  PublicRouteTableId:
    Description: PublicRouteTable ID
    Type: String
  StackName:
    Description: Name of the Stack
    Type: String
    AllowedPattern: '[a-zA-Z0-9_\-]*'
    ConstraintDescription: must be alphanumeric
Mappings:
  PublicSubnetConfig:
    NatPublicSubnet03:
      CIDR: 10.0.0.0/28
Resources:
  NatPublicSubnet03:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub
        - ${AZ}
        - AZ: !Select
            - 0
            - !GetAZs
      CidrBlock: !FindInMap
        - PublicSubnetConfig
        - NatPublicSubnet03
        - CIDR
      VpcId: !Ref VpcId
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - NatPublicSubnet03
        - Key: Env
          Value: !Ref Environment
  PublicSubnetRouteTableAssociation03:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTableId
      SubnetId: !Ref NatPublicSubnet03
  NatEIP03:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - NatEIP03
        - Key: Env
          Value: !Ref Environment
  NatGateway03:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEIP03.AllocationId
      SubnetId: !Ref NatPublicSubnet03
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - NatGateway03
        - Key: Env
          Value: !Ref Environment
Outputs:
  NatGateway03:
    Description: NatGateway03 ID
    Value: !Ref NatGateway03
  NatPublicSubnet03:
    Description: NatPublicSubnet03 ID
    Value: !Ref NatPublicSubnet03

