# nat-stack.yaml
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
  VpcId:
    Description: VPC ID
    Type: String
  PublicRouteTableId:
    Description: PublicRouteTable ID
    Type: String
  StackName:
    Description: Name of the Stack
    Type: String
    AllowedPattern: '[a-zA-Z0-9_\-]*'
    ConstraintDescription: must be alphanumeric
Mappings:
  PublicSubnetConfig:
    NatPublicSubnet02:
      CIDR: 10.0.0.16/28
Resources:
  NatPublicSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub
        - ${AZ}
        - AZ: !Select
            - 0
            - !GetAZs
      CidrBlock: !FindInMap
        - PublicSubnetConfig
        - NatPublicSubnet02
        - CIDR
      VpcId: !Ref VpcId
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - NatPublicSubnet02
        - Key: Env
          Value: !Ref Environment
  PublicSubnetRouteTableAssociation02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTableId
      SubnetId: !Ref NatPublicSubnet02
  NatEIP02:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - NatEIP02
        - Key: Env
          Value: !Ref Environment
  NatGateway02:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEIP02.AllocationId
      SubnetId: !Ref NatPublicSubnet02
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - NatGateway02
        - Key: Env
          Value: !Ref Environment
Outputs:
  NatGateway02:
    Description: NatGateway02 ID
    Value: !Ref NatGateway02
  NatPublicSubnet02:
    Description: NatPublicSubnet02 ID
    Value: !Ref NatPublicSubnet02
