# vpc-stack.yaml
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
Mappings:
  VpcConfig:
    VPC:
      CIDR: 10.0.0.0/16
    PublicSubnet01:
      CIDR: 10.0.0.0/28
    PublicSubnet02:
      CIDR: 10.0.0.16/28
    PublicSubnet03:
      CIDR: 10.0.0.32/28
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      CidrBlock: !FindInMap
        - VpcConfig
        - VPC
        - CIDR
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: VPC
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - VPC
  InternetGateway: 
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - IGW
  AttachIgwGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: 
    - VPC
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - IGW-VPC
  DefaultNetworkACL: 
    Type: AWS::EC2:NetworkAcl
    DependsOn : 
    - VPC
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - DefaultNetworkACL
  DefaultInboundNetworkACL: 
    Type: AWS::EC2::NetworkAclEntry
    DependsOn : 
    - VPC
    Properties:
      NetworkAclId: !Ref DefaultNetworkACL
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - DefaultInboundNetworkACL
Outputs:
  VPC:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPC"
  IGW:
    Description: IGW ID
    Value: !Ref IGW
    Export:
      Name: !Sub "${AWS::StackName}-IGW"
  DefaultNetworkACL:
    Description: DefaultNetworkACL ID
    Value: !Ref DefaultNetworkACL
    Export:
      Name: !Sub "${AWS::StackName}-DefaultNetworkACL"
