# main-stack.yaml
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
      - dev
      - test
      - uat
      - prod
  BastionHostKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: ./vpc-stack.yaml
      Parameters:
        Environment: !Ref Environment
        StackName: !Ref AWS::StackName
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - VpcStack
        - Key: Env
          Value: !Ref Environment
  PublicSubnets:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: ./public-subnets.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        IgwId: !GetAtt VpcStack.Outputs.IgwId
        StackName: !Ref AWS::StackName
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - PublicSubnets
        - Key: Env
          Value: !Ref Environment
  NatGateway01:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: ./nat01-stack.yaml
      Parameters:
        Environment: !Ref Environment
        PublicSubnet01Id: !GetAtt PublicSubnets.Outputs.PublicSubnet01Id
        StackName: !Ref AWS::StackName
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - NatGateway01
        - Key: Env
          Value: !Ref Environment
  PrivateSubnets:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: ./application-subnets.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        NatGateway01Id: !GetAtt NatGateway01.Outputs.NatGateway01Id
        StackName: !Ref AWS::StackName
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - PrivateSubnets
        - Key: Env
          Value: !Ref Environment
  BastionHost:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: ./bastion-host-stack.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PublicSubnet01Id: !GetAtt PublicSubnets.Outputs.PublicSubnet01Id
        StackName: !Ref AWS::StackName
        KeyName: !Ref BastionHostKeyName
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - BastionHost
        - Key: Env
          Value: !Ref Environment
  WebAppLoadBalancer:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: ./web-load-balancer.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PublicSubnet01Id: !GetAtt PublicSubnets.Outputs.PublicSubnet01Id
        PublicSubnet02Id: !GetAtt PublicSubnets.Outputs.PublicSubnet02Id
        PublicSubnet03Id: !GetAtt PublicSubnets.Outputs.PublicSubnet03Id
        StackName: !Ref AWS::StackName
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - WebAppLoadBalancer
        - Key: Env
          Value: !Ref Environment
  HelloApplication:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: ./hello-application.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PrivateAppSubnet01Id: !GetAtt PrivateSubnets.Outputs.PrivateAppSubnet01Id
        PrivateAppSubnet02Id: !GetAtt PrivateSubnets.Outputs.PrivateAppSubnet02Id
        PrivateAppSubnet03Id: !GetAtt PrivateSubnets.Outputs.PrivateAppSubnet03Id
        WebLoadBalancerArnName: !GetAtt WebAppLoadBalancer.Outputs.WebLoadBalancerArnName
        StackName: !Ref AWS::StackName
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - HelloApplication
        - Key: Env
          Value: !Ref Environment
