# nat-stack.yaml
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
      - dev
      - test
      - uat
      - prod
  PublicSubnet01Id:
    Description: PublicSubnet01 ID
    Type: String
  StackName:
    Description: Name of the Stack
    Type: String
    AllowedPattern: '[a-zA-Z0-9_\-]*'
    ConstraintDescription: must be alphanumeric
Resources:
  NatEIP01:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - NatEIP01
        - Key: Env
          Value: !Ref Environment
  NatGateway01:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEIP01.AllocationId
      SubnetId: !Ref PublicSubnet01Id
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - NatGateway01
        - Key: Env
          Value: !Ref Environment
Outputs:
  NatGateway01Id:
    Description: NatGateway01 ID
    Value: !Ref NatGateway01

