# public-subnets.yaml
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
  VpcId:
    Description: VPC ID
    Type: String
  IgwId:
    Description: Internet Gateway ID
    Type: String
  StackName:
    Description: Name of the Stack
    Type: String
    AllowedPattern: '[a-zA-Z0-9_\-]*'
    ConstraintDescription: must be alphanumeric
Mappings:
  PublicSubnetConfig:
    PublicSubnet01:
      CIDR: 10.0.0.0/28
    PublicSubnet02:
      CIDR: 10.0.0.16/28
    PublicSubnet03:
      CIDR: 10.0.0.32/28
Resources:
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - PublicRouteTable
        - Key: Env
          Value: !Ref Environment
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref IgwId
  PublicSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub
        - ${AZ}
        - AZ: !Select
            - 0
            - !GetAZs
      CidrBlock: !FindInMap
        - PublicSubnetConfig
        - PublicSubnet01
        - CIDR
      VpcId: !Ref VpcId
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - PublicSubnet01
        - Key: Env
          Value: !Ref Environment
  PublicSubnetRouteTableAssociation01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet01
  PublicSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub
        - ${AZ}
        - AZ: !Select
            - 1
            - !GetAZs
      CidrBlock: !FindInMap
        - PublicSubnetConfig
        - PublicSubnet02
        - CIDR
      VpcId: !Ref VpcId
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - PublicSubnet02
        - Key: Env
          Value: !Ref Environment
  PublicSubnetRouteTableAssociation02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet02
  PublicSubnet03:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub
        - ${AZ}
        - AZ: !Select
            - 2
            - !GetAZs
      CidrBlock: !FindInMap
        - PublicSubnetConfig
        - PublicSubnet03
        - CIDR
      VpcId: !Ref VpcId
      Tags:
        - Key: Application
          Value: !Ref StackName
        - Key: Network
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - PublicSubnet03
        - Key: Env
          Value: !Ref Environment
  PublicSubnetRouteTableAssociation03:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet03
Outputs:
  PublicSubnet01Id:
    Description: PublicSubnet01 ID
    Value: !Ref PublicSubnet01
  PublicSubnet02Id:
    Description: PublicSubnet02 ID
    Value: !Ref PublicSubnet02
  PublicSubnet03Id:
    Description: PublicSubnet03 ID
    Value: !Ref PublicSubnet03
