AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
      - dev
      - test
      - uat
      - prod
  StackName:
    Description: Name of the Stack
    Type: String
    AllowedPattern: '[a-zA-Z0-9_\-]*'
    ConstraintDescription: must be alphanumeric
  CodePipelineServiceRoleArn:
    Description: CodePipeline Service Role ARN
    Type: String
  GitHubConnectionArn:
    Description: GitHub Connection ARN
    Type: String
  GitHubRepositoryName:
    Description: GitHub Repository Name
    Type: String
    Default: aws-cf-infra-template
  GitHubBranchName:
    Description: GitHub Branch Name
    Type: String
    Default: Dev
  CodeBuildProject:
    Description: CodeBuild Project
    Type: String
  ArtifactBucket:
    Description: Artifact Bucket
    Type: String
Resources:
  # CodePipeline
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${StackName}-${Environment}-pipeline"
      PipelineType: V2
      RoleArn: !Ref CodePipelineServiceRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: !Sub "${StackName}-${Environment}-githubsource"
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ConnectionArn: !Ref GitHubConnectionArn
                FullRepositoryId: !Ref GitHubRepositoryName
                BranchName: !Ref GitHubBranchName
                DetectChanges: true
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1
      Triggers:
        - ProviderType: CodeStarSourceConnection
          GitConfiguration:
            SourceActionName: !Sub "${StackName}-${Environment}-githubsource"
            Push:
              - Branches:
                  Includes: [!Ref GitHubBranchName]                    
                FilePaths:
                  Includes: ['infra/*']
                  Excludes: ['pipeline/*', 'github/*', '.gitignore','deploy', 'README.md', 'LICENSE', 'setup-pipeline', 'verify']                         
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Tags:
        - Key: Deployment
          Value: !Ref StackName
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - CodePipeline
        - Key: Env
          Value: !Ref Environment
