AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
      - dev
      - test
      - uat
      - prod
  StackName:
    Description: Name of the Stack
    Type: String
    AllowedPattern: '[a-zA-Z0-9_\-]*'
    ConstraintDescription: must be alphanumeric
  CodeBuildServiceRoleArn:
    Description: CodeBuild Service Role ARN
    Type: String
  CloudFormationServiceRoleArn:
    Description: CloudFormation Service Role ARN
    Type: String
  CfPackageBucket:
    Description: S3 Bucket for CloudFormation package
    Type: String
  BastionHostKeyName:  
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
    AllowedPattern: '[a-zA-Z0-9_\-]*'
    ConstraintDescription: must be alphanumeric
Resources:
  # Log Group for Deployment
  DeploymentLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub "/codebuild/${StackName}/${Environment}/deployment"
      RetentionInDays: 7
      Tags:
        - Key: Deployment
          Value: !Ref StackName
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - DeploymentLogGroup
        - Key: Env
          Value: !Ref Environment
  # CodeBuild Project
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${StackName}-${Environment}-codebuild"
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables: 
          - Name: TARGET_ENV
            Value: !Ref Environment
            Type: PLAINTEXT
          - Name: REGION
            Value: !Ref AWS::Region
            Type: PLAINTEXT
          - Name: S3_BUCKET
            Value: !Ref CfPackageBucket
            Type: PLAINTEXT
          - Name: STACKNAME
            Value: !Ref StackName
            Type: PLAINTEXT
          - Name: BASTION_HOST_KEY_NAME
            Value: !Ref BastionHostKeyName
            Type: PLAINTEXT
          - Name: ROLE_ARN
            Value: !Ref CloudFormationServiceRoleArn
            Type: PLAINTEXT
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Ref DeploymentLogGroup
          StreamName: "codebuild"
      ServiceRole: !Ref CodeBuildServiceRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                python: 3.8
            build:
              commands:
                - ./deploy
      Tags:
        - Key: Deployment
          Value: !Ref StackName
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - CodeBuildProject
        - Key: Env
          Value: !Ref Environment
Outputs:
  CodeBuildProject:
    Description: CodeBuild Project
    Value: !Ref CodeBuildProject
