AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
      - dev
      - test
      - uat
      - prod
  BastionHostKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
  GitHubConnectionArn:
    Description: GitHub Connection ARN
    Type: String
  GitHubRepositoryName:
    Description: GitHub Repository Name
    Type: String
    Default: aws-cf-infra-template
  GitHubBranchName:
    Description: GitHub Branch Name
    Type: String
Resources:
  RolesStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: ./roles-stack.yaml
      Parameters:
        Environment: !Ref Environment
        StackName: !Ref AWS::StackName
      Tags:
        - Key: Deployment
          Value: !Ref AWS::StackName
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - RolesStack
        - Key: Env
          Value: !Ref Environment
  S3BucketStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: ./s3-bucket-stack.yaml
      Parameters:
        Environment: !Ref Environment
        StackName: !Ref AWS::StackName
      Tags:
        - Key: Deployment
          Value: !Ref AWS::StackName
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - S3BucketStack
        - Key: Env
          Value: !Ref Environment
  CodeBuildStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: ./codebuild-stack.yaml
      Parameters:
        Environment: !Ref Environment
        StackName: !Ref AWS::StackName
        CodeBuildServiceRoleArn: !GetAtt RolesStack.Outputs.CodeBuildServiceRoleArn
        CloudFormationServiceRoleArn: !GetAtt RolesStack.Outputs.CloudFormationServiceRoleArn
        CfPackageBucket: !GetAtt S3BucketStack.Outputs.CfPackageBucket
        BastionHostKeyName: !Ref BastionHostKeyName
      Tags:
        - Key: Deployment
          Value: !Ref AWS::StackName
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - CodeBuildStack
        - Key: Env
          Value: !Ref Environment
  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: ./codepipeline-stack.yaml
      Parameters:
        Environment: !Ref Environment
        StackName: !Ref AWS::StackName
        CodePipelineServiceRoleArn: !GetAtt RolesStack.Outputs.CodePipelineServiceRoleArn
        GitHubConnectionArn: !Ref GitHubConnectionArn
        GitHubRepositoryName: !Ref GitHubRepositoryName
        GitHubBranchName: !Ref GitHubBranchName
        CodeBuildProject: !GetAtt CodeBuildStack.Outputs.CodeBuildProject
        ArtifactBucket: !GetAtt S3BucketStack.Outputs.ArtifactBucket
      Tags:
        - Key: Deployment
          Value: !Ref AWS::StackName
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - !Ref Environment
              - CodePipelineStack
        - Key: Env
          Value: !Ref Environment





