AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
      - dev
      - test
      - uat
      - prod
  StackName:
    Description: Name of the Stack
    Type: String
    AllowedPattern: '[a-zA-Z0-9_\-]*'
    ConstraintDescription: must be alphanumeric
Resources:
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - "-"
        - - !Ref StackName
          - !Ref Environment
          - CodePipelineServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${StackName}-${Environment}-CodePipelineServicePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "codepipeline:*"
                  - "s3:*"
                  - "codebuild:*"
                  - "codestar-connections:UseConnection"
                Resource: "*"
      Tags:
        - Key: Deployment
          Value: !Ref StackName
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - CodePipelineServiceRole
        - Key: Env
          Value: !Ref Environment
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - "-"
        - - !Ref StackName
          - !Ref Environment
          - CodeBuildServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${StackName}-${Environment}-CodeBuildServicePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:GetBucketVersioning"
                  - "s3:GetObjectVersion"
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "ecr:GetAuthorizationToken"
                  - "ssm:GetParameters"
                Resource: "*"
      Tags:
        - Key: Deployment
          Value: !Ref StackName
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - CodeBuildServicePolicy
        - Key: Env
          Value: !Ref Environment
  CloudFormationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - "-"
        - - !Ref StackName
          - !Ref Environment
          - CloudFormationServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${StackName}-${Environment}-CloudFormationServiceRole"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # IAM Role Management
              - Effect: Allow
                Action:
                  - "iam:CreateRole"
                  - "iam:DeleteRole"
                  - "iam:AttachRolePolicy"
                  - "iam:DetachRolePolicy"
                  - "iam:PutRolePolicy"
                  - "iam:GetRole"
                  - "iam:GetRolePolicy"
                  - "iam:ListRolePolicies"
                  - "iam:ListAttachedRolePolicies"
                  - "iam:DeleteRolePolicy"
                  - "iam:UpdateRole"
                Resource: "*"
              # CloudWatch Logs
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogGroups"
                  - "logs:DescribeLogStreams"
                Resource: "*"
              # S3 Bucket Access
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource: "*"
              # VPC and Networking
              - Effect: Allow
                Action:
                  - "ec2:CreateVpc"
                  - "ec2:DeleteVpc"
                  - "ec2:DescribeVpcs"
                  - "ec2:CreateSubnet"
                  - "ec2:DeleteSubnet"
                  - "ec2:DescribeSubnets"
                  - "ec2:CreateInternetGateway"
                  - "ec2:DeleteInternetGateway"
                  - "ec2:AttachInternetGateway"
                  - "ec2:DetachInternetGateway"
                  - "ec2:CreateNatGateway"
                  - "ec2:DeleteNatGateway"
                  - "ec2:DescribeNatGateways"
                  - "ec2:AllocateAddress"
                  - "ec2:ReleaseAddress"
                  - "ec2:DescribeAddresses"
                  - "ec2:DescribeKeyPairs"
                  - "ec2:CreateRouteTable"
                  - "ec2:DeleteRouteTable"
                  - "ec2:DescribeRouteTables"
                  - "ec2:CreateRoute"
                  - "ec2:DeleteRoute"
                  - "ec2:AssociateRouteTable"
                  - "ec2:DisassociateRouteTable"
                  - "ec2:ReplaceRoute"
                  - "ec2:ReplaceRouteTableAssociation"
                  - "ec2:CreateNetworkAcl"
                  - "ec2:DeleteNetworkAcl"
                  - "ec2:DescribeNetworkAcls"
                  - "ec2:CreateNetworkAclEntry"
                  - "ec2:DeleteNetworkAclEntry"
                  - "ec2:ReplaceNetworkAclAssociation"
                  - "ec2:ReplaceNetworkAclEntry"
                Resource: "*"
              # EC2 Management
              - Effect: Allow
                Action:
                  - "ec2:RunInstances"
                  - "ec2:TerminateInstances"
                  - "ec2:DescribeInstances"
                  - "ec2:CreateTags"
                  - "ec2:DeleteTags"
                Resource: "*"
              # ECS Management
              - Effect: Allow
                Action:
                  - "ecs:CreateCluster"
                  - "ecs:DeleteCluster"
                  - "ecs:DescribeClusters"
                  - "ecs:CreateService"
                  - "ecs:UpdateService"
                  - "ecs:DeleteService"
                  - "ecs:DescribeServices"
                  - "ecs:RegisterTaskDefinition"
                  - "ecs:DeregisterTaskDefinition"
                  - "ecs:DescribeTaskDefinition"
                  - "ecs:RunTask"
                  - "ecs:StopTask"
                  - "ecs:DescribeTasks"
                Resource: "*"
      Tags:
        - Key: Deployment
          Value: !Ref StackName
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - CloudFormationServiceRole
        - Key: Env
          Value: !Ref Environment
Outputs:
  CodePipelineServiceRoleArn:
    Description: CodePipeline Service Role Arn
    Value: !GetAtt CodePipelineServiceRole.Arn
  CodeBuildServiceRoleArn:
    Description: CodeBuild Service Role Arn
    Value: !GetAtt CodeBuildServiceRole.Arn
  CloudFormationServiceRoleArn:
    Description: CloudFormation Service Role Arn
    Value: !GetAtt CloudFormationServiceRole.Arn
