AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Description: Name of Environments
    Type: String
    AllowedValues:
      - Dev
      - Test
      - UAT
      - Prod
      - dev
      - test
      - uat
      - prod
  StackName:
    Description: Name of the Stack
    Type: String
    AllowedPattern: '[a-zA-Z0-9_\-]*'
    ConstraintDescription: must be alphanumeric
Resources:
  # S3 Bucket for Artifacts
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${Environment}-artifacts"
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Deployment
          Value: !Ref StackName
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - ArtifactBucket
        - Key: Env
          Value: !Ref Environment
  # S3 Bucket For CloudFormation package
  CfPackageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StackName}-${Environment}-cfpackage"
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Deployment
          Value: !Ref StackName
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref StackName
              - !Ref Environment
              - CfPackageBucket
        - Key: Env
          Value: !Ref Environment
Outputs:
  ArtifactBucket:
    Description: S3 Bucket for Artifacts
    Value: !Ref ArtifactBucket
  CfPackageBucket:
    Description: S3 Bucket For CloudFormation package
    Value: !Ref CfPackageBucket
